spring.application.name=BookStore-Security

spring.datasource.url=jdbc:mysql://localhost:3306/myspringdb2?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Harshit#98pllrcv8

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

jwt.secret=hklPa2OEkpESeYh0Yezj+LgnYvzOpQ1lBf2s1MBUCgQ=
jwt.expiration=86400000

cors.allowed-origins=http://localhost:3000,http://localhost:4200